In [59]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
np.__version__

'1.19.5'

In [60]:
pd.__version__

'1.3.2'

In [50]:
file_path = '../input/carpriceprediction/data.csv'
data_df = pd.read_csv(file_path)
data_df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
# What's the average price of BMW cars in the dataset?
data_df[data_df['Make']=="BMW"].MSRP.mean()

61546.76347305389

In [13]:
#Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?
data_df[data_df['Year']>=2015]["Engine HP"].isnull().sum()

51

In [28]:
# Question 5
mean_hp_before = data_df['Engine HP'].mean()
print(data_df['Engine HP'].isnull().sum())
data_df['Engine HP'].fillna(mean_hp_before)
mean_hp_after =data_df['Engine HP'].mean()
print(round(mean_hp_before))
print(round(mean_hp_after))

69
249
249


In [54]:
# Question 6
data_roll = data_df[data_df['Make']== "Rolls-Royce"]
data_roll_filtered = data_roll[["Engine HP", "Engine Cylinders", "highway MPG"]]
data_roll_filtered = data_roll_filtered.drop_duplicates()
data_roll_filtered

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [55]:
# get numpy array
x = data_roll_filtered.values
print(x)

[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]


In [56]:
# Question 6
x_transpose = x.T
x_out = x_transpose.dot(x)
x_inv =  np.linalg.inv(x_out)
print(x_inv.sum())

0.032212320677486125


In [58]:
# Questions 7
y = [1000, 1100, 900, 1200, 1000, 850, 1300]
w = (x_inv.dot(x_transpose)).dot(y)
print(w)

[ 0.19989598 31.02612262 31.65378877]
